const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chrome'});
 const page=await browser.newPage({viewport:{width:1440,height:960}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/api/active-job',r=>r.fulfill({json:null}));
 await page.goto(process.env.APP_URL || 'http://127.0.0.1:5178');
 await page.getByRole('button',{name:'New project',exact:true}).click();
 await page.locator('.project-type-cards button').filter({hasText:'Jigsaw puzzle'}).click();
 await page.getByRole('button',{name:'Create project',exact:true}).click();
 await page.getByRole('button',{name:'Artwork layout',exact:true}).click();
 const svg=page.locator('.puzzle-layout svg');await svg.waitFor();
 const before=await svg.locator('path').first().getAttribute('d');
 await page.getByRole('button',{name:'Reshuffle piece pattern'}).click();
 const after=await svg.locator('path').first().getAttribute('d');assert.notEqual(before,after);
 await page.getByRole('button',{name:'Undo design change'}).click();assert.equal(await svg.locator('path').first().getAttribute('d'),before);
 await page.getByRole('button',{name:/Easy.*pieces/}).click();assert.match(await page.locator('.puzzle-layout h3').textContent(),/^9 pieces/);
 await page.getByRole('button',{name:'Show piece numbers'}).click();assert.equal(await svg.locator('text').count(),9);
 await page.getByRole('button',{name:'Round tabs',exact:true}).click();assert.match(await svg.locator('path').first().getAttribute('d'),/A/);
 await page.getByRole('button',{name:'Classic jigsaw',exact:true}).click();
 await page.getByRole('button',{name:/Balanced.*pieces/}).click();
 await page.screenshot({path:'data/jigsaw-upgrade-desktop.png'});
 await page.waitForTimeout(700);await page.reload();await page.getByRole('button',{name:'Continue last project',exact:true}).click();
 await page.getByRole('button',{name:'Artwork layout',exact:true}).click();assert.match(await page.locator('.puzzle-layout h3').textContent(),/^25 pieces/);
 const saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('contour-studio.draft.v1')).settings);
 assert.equal(saved.puzzle_style,'classic');assert.equal(saved.puzzle_seed,1);
 const response=await page.request.post(new URL('/api/validate',page.url()).href,{data:saved});assert(response.ok(),await response.text());
 await page.setViewportSize({width:390,height:844});
 await page.locator('.puzzle-layout').scrollIntoViewIfNeeded();
 await page.screenshot({path:'data/jigsaw-upgrade-mobile.png'});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 assert.deepEqual(errors,[]);
 console.log('PASS jigsaw presets, reshuffle, undo, round/classic preview, numbers, saved reload, API validation and mobile overflow');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
