// Regression coverage for design recovery and customisation against the local API.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || "playwright");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const { reveal } = require("./ui-helpers.cjs");
const url = process.env.APP_URL || "http://127.0.0.1:8765";
(async () => {
  const browser = await chromium.launch({ channel: "chrome", headless: true });
  const page = await browser.newPage({ baseURL: url, viewport: { width: 1440, height: 1000 }, acceptDownloads: true });
  const errors = [];
  page.on("pageerror", (error) => errors.push(error.message));
  const button = (name) => page.getByRole("button", { name, exact: true, includeHidden: true });
  const readSettings = async () => {
    const saveButton = page.locator(".sidebar").getByRole("button", { name: "Save settings", exact: true, includeHidden: true });
    await reveal(page, saveButton);
    const pending = page.waitForEvent("download");
    await saveButton.click();
    return JSON.parse(fs.readFileSync(await (await pending).path(), "utf8"));
  };
  const draftIs = async (field, value) => page.waitForFunction(([key, expected]) => {
    const draft = JSON.parse(localStorage.getItem("contour-studio.draft.v1") || "null");
    return draft?.settings?.[key] === expected;
  }, [field, value]);
  try {
    await page.goto(url);
    await button("Make it yours").waitFor();
    await page.locator(".maplibregl-canvas").waitFor();
    const width = page.getByLabel("Width · mm", { exact: true });
    await width.fill("");
    assert.equal((await readSettings()).width, 600, "blank width keeps the valid design");
    await width.fill("9999");
    assert.equal(await width.getAttribute("aria-invalid"), "true");
    assert.equal((await readSettings()).width, 2000, "blur constrains width to its supported range");
    await button("Undo design change").click();
    assert.equal(await width.inputValue(), "600");
    await page.getByLabel("Keep proportions", { exact: true }).check();
    await width.fill("450");
    await width.press("Tab");
    assert.equal(await page.getByLabel("Height · mm", { exact: true }).inputValue(), "300");
    await button("Undo design change").click();
    assert.equal(await width.inputValue(), "600");
    await button("Redo design change").click();
    assert.equal(await width.inputValue(), "450");
    await page.getByLabel("Keep proportions", { exact: true }).uncheck();
    await button("Classic 600 × 400").click();
    await reveal(page, page.getByText("Change printer settings", { exact: true }));
    await page.getByText("Change printer settings", { exact: true }).click();
    await page.getByRole("button", { name: /^Bambu Lab P1S 256/ }).click();
    assert.equal((await readSettings()).printer_width, 256);
    await reveal(page, button("Custom"));
    await button("Custom").click();
    await page.getByLabel("Columns", { exact: true }).fill("2.5");
    await page.getByLabel("Columns", { exact: true }).press("Tab");
    assert.equal(await page.getByLabel("Columns", { exact: true }).inputValue(), "3");
    await page.getByLabel("Columns", { exact: true }).fill("1");
    await page.getByLabel("Rows", { exact: true }).fill("1");
    await draftIs("columns", 1);
    await page.reload();
    await page.locator(".tile-summary.invalid").waitFor();
    assert.equal(await page.getByLabel("Columns", { exact: true }).inputValue(), "1", "even an invalid in-progress layout is recovered");
    await button("Automatic").click();
    await page.getByLabel("Map appearance", { exact: true }).selectOption("colour");
    await button("Make it yours").click();
    await reveal(page, page.getByRole("button", { name: /^Landscape Hills/, includeHidden: true }));
    await page.getByRole("button", { name: /^Landscape Hills/, includeHidden: true }).click();
    assert.equal((await readSettings()).buildings, false);
    await page.getByRole("button", { name: /^Contour art Visible/, includeHidden: true }).click();
    await reveal(page, button("Slim"));
    await button("Slim").click();
    await page.getByText("Your style presets", { exact: true }).click();
    await page.getByLabel("Custom style name", { exact: true }).fill("My contour style");
    await button("Save style").click();
    await button("Natural").click();
    await button("My contour style").click();
    let saved = await readSettings();
    assert.equal(saved.terrain_style, "terraced");
    assert.equal(saved.frame_width, 6);
    await reveal(page, button("Add a special place"));
    await button("Add a special place").click();
    await page.getByLabel("Place 1 name", { exact: true }).fill("Home");
    await button("Cancel placement").click();
    await button("Duplicate place 1").click();
    await button("Cancel placement").click();
    saved = await readSettings();
    assert.equal(saved.markers.length, 2);
    assert.notEqual(saved.markers[0].id, saved.markers[1].id);
    await draftIs("terrain_style", "terraced");
    await page.waitForFunction(() => JSON.parse(localStorage.getItem("contour-studio.draft.v1")).settings.markers.length === 2);
    await page.reload();
    await page.getByRole("heading", { name: "Make it yours.", exact: true }).waitFor();
    saved = await readSettings();
    assert.equal(saved.markers[0].label, "Home");
    assert.equal(saved.frame_width, 6);
    assert.equal(saved.terrain_style, "terraced");
    await page.locator("input[type=file]").setInputFiles({ name: "invalid.json", mimeType: "application/json", buffer: Buffer.from(JSON.stringify({ ...saved, width: 9000 })) });
    await page.getByRole("alert").filter({ hasText: "Could not import settings" }).waitFor();
    assert.equal((await readSettings()).width, 600, "invalid imports leave the current design intact");
    await button("My projects").click();
    await page.getByLabel("Search saved projects", { exact: true }).fill("no-artwork-can-have-this-name");
    await page.getByText("No matching artworks.", { exact: true }).waitFor();
    await button("Clear search").click();
    await page.getByLabel("Sort saved projects", { exact: true }).selectOption("name");
    await page.keyboard.press("Escape");
    await button("Dismiss error").click();
    for (const size of [{ width: 390, height: 844 }, { width: 768, height: 900 }, { width: 1440, height: 1000 }]) {
      await page.setViewportSize(size);
      assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), "workspace fits the viewport");
      const footer = await page.locator(".workflow-footer").boundingBox();
      assert(footer.y >= 0 && footer.y + footer.height <= size.height + 1, "primary action remains visible");
    }
    await page.locator(".sidebar").evaluate((element) => element.scrollTo({ top: 0 }));
    await page.screenshot({ path: "data/polish-style-desktop.png" });
    assert.deepEqual(errors, []);
    console.log("PASS: safe numeric edits, proportions, undo/redo, printers, integer tiling, invalid-draft recovery, reusable styles, marker duplication, refresh, validated import, searchable library and responsive layout; no page errors.");
  } finally { await browser.close(); }
})().catch((error) => { console.error(error); process.exitCode = 1; });
