"""Make the website's display mesh from an existing generated multicolour preview.

Usage: python scripts/build-showcase.py PATH/TO/preview.glb
Requires trimesh and fast-simplification (asset tooling only).
The print files are never modified. Mesh names preserve tiles and colour regions.
"""
from pathlib import Path
import argparse
import json
import numpy as np
import trimesh

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("preview", type=Path)
args = parser.parse_args()
source = trimesh.load(args.preview, force="scene", process=False)
result = trimesh.Scene()
limits = {"ground": 14000, "roads": 10000, "buildings": 7000, "fields": 6000,
          "water": 3000, "forest": 2500, "frame": 3000}
before = after = 0
for node in source.graph.nodes_geometry:
    transform, geometry_name = source.graph[node]
    mesh = source.geometry[geometry_name].copy()
    mesh.apply_transform(transform)
    # Snap sub-pixel boolean detail to a shared 0.15 mm grid before decimation.
    # All regions use the same grid so their adjoining surfaces stay aligned.
    mesh.vertices = np.round(mesh.vertices / 0.15) * 0.15
    mesh.merge_vertices()
    mesh.update_faces(mesh.nondegenerate_faces())
    mesh.update_faces(mesh.unique_faces())
    mesh.remove_unreferenced_vertices()
    region = node.rsplit("_", 1)[-1]
    if region not in limits or not node.startswith("MaterialVisual_"):
        raise ValueError(f"Unexpected showcase geometry: {node}")
    before += len(source.geometry[geometry_name].faces)
    if len(mesh.faces) > limits[region]:
        mesh = mesh.simplify_quadric_decimation(face_count=limits[region], aggression=7)
    # Positions and indices only. Lighting normals are generated by the viewer.
    mesh.visual = trimesh.visual.ColorVisuals(mesh=mesh)
    mesh.metadata.clear()
    after += len(mesh.faces)
    result.add_geometry(mesh, node_name=node, geom_name=node)
output = Path(__file__).resolve().parents[1] / "public" / "showcase.glb"
output.write_bytes(result.export(file_type="glb", include_normals=False))
print(json.dumps({"asset": str(output), "source_triangles": before,
                  "display_triangles": after, "bytes": output.stat().st_size}))
