import { Plus } from 'lucide-react';
import type { Settings } from './types';
import { collectionCells, continuousWall, modularWall, wallAdditions } from './formats';
export default function CollectionLayout({settings:s,onTile,onGrow,onAdd}:{settings:Settings;onTile:(i:number)=>void;onGrow?:(direction:"column"|"row")=>void;onAdd?:(position:[number,number])=>void}) {
  const cells=collectionCells(s),continuous=continuousWall(s),modular=modularWall(s);
  const additions=modular&&onAdd?wallAdditions(s).map(position=>({position,cell:collectionCells({...s,wall_positions:[position]})[0]})):[];
  const points=[...cells,...additions.map(a=>a.cell)].flatMap(c=>c.points);
  const width=Math.max(s.width,...points.map(p=>p[0]))+12,height=Math.max(s.height,...points.map(p=>p[1]))+12;
  return <div className="collection-layout"><div><span className="eyebrow">ONGOING TILE PROJECT</span><h3>{continuous?'Your continuous map':'Your collection of places'}</h3><p>{s.map_tiles.length} {continuous?'map tiles':'places'} · {s.width.toFixed(1)} × {s.height.toFixed(1)} mm</p></div><svg viewBox={`-8 -8 ${width+8} ${height+8}`} role="group" aria-label="Collection arrangement">
    {cells.map((cell,i)=><g key={s.map_tiles[i]?.id??i} role="button" tabIndex={0} aria-label={`Edit tile ${i+1}: ${continuous?s.name:s.map_tiles[i]?.name??'Map'}`} onClick={()=>onTile(i)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onTile(i);}}}><polygon points={cell.points.map(p=>p.join(',')).join(' ')} fill={s.colour_ground} stroke={i===s.active_tile?'#ac412b':s.colour_frame} strokeWidth={i===s.active_tile?1.5:1}/><text x={cell.x} y={cell.y-5} textAnchor="middle" fontSize={5} fill="#20372c">{i+1}</text><text x={cell.x} y={cell.y+4} textAnchor="middle" fontSize={4} fill="#20372c">{(continuous?s.name:s.map_tiles[i]?.name??'Map').slice(0,22)}</text>{s.mount_mode==='magnets'&&[-.23,.23].map(f=><circle key={f} cx={cell.x+s.tile_size*f} cy={cell.y} r={s.magnet_diameter/2} fill="none" stroke="#344b40" strokeDasharray="1 1" strokeWidth={.4}/>)}</g>)}
    {additions.map(({position,cell})=><g key={position.join(',')} role="button" tabIndex={0} aria-label={`Add tile at row ${position[0]+1}, column ${position[1]+1}`} onClick={()=>onAdd?.(position)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onAdd?.(position);}}}><polygon points={cell.points.map(p=>p.join(',')).join(' ')} fill="#f7f8f3" stroke="#809285" strokeDasharray="3 2" strokeWidth={.7}/><Plus x={cell.x-5} y={cell.y-5} width={10} height={10} stroke="#344b40"/></g>)}
  </svg>{!modular&&onGrow&&<div className="wall-grow-actions"><button type="button" disabled={s.collection_columns>=6} onClick={()=>onGrow('column')}>Add column</button><button type="button" disabled={s.collection_rows>=6} onClick={()=>onGrow('row')}>Add row</button></div>}<p className="hint">{modular?`Select an adjoining + to add one tile. ${continuous?'The map extends at the same geographic scale.':'Choose the new tile’s place in Place.'} Existing locations and details stay saved. Up to 36 tiles per project.`:'Select a tile to choose its location.'} Dashed circles show magnet positions. Terrain appears after generation.</p></div>;
}
