import { Plus, Trash2 } from 'lucide-react';
import type { Settings } from './types';
import { collectionCells, continuousWall, modularWall, wallAdditions } from './formats';
export default function CollectionLayout({settings:s,onTile,onGrow,onAdd,onRemove}:{settings:Settings;onTile:(i:number)=>void;onGrow?:(direction:"column"|"row")=>void;onAdd?:(position:[number,number])=>void;onRemove?:(index:number)=>void}) {
  const cells=collectionCells(s),continuous=continuousWall(s),modular=modularWall(s),pucks=modular&&(s.hang_mode==='pucks'||s.hang_mode==='magnet_pucks');
  const additions=modular&&onAdd?wallAdditions(s).map(position=>({position,cell:collectionCells({...s,wall_positions:[position]})[0]})):[];
  const points=[...cells,...additions.map(a=>a.cell)].flatMap(c=>c.points);
  const minX=Math.min(0,...points.map(p=>p[0])),maxX=Math.max(s.width,...points.map(p=>p[0])),minY=Math.min(0,...points.map(p=>p[1])),maxY=Math.max(s.height,...points.map(p=>p[1]));
  // Printed tiles count rows from the south, so the drawing is turned north-up to match the assembly guide.
  const up=(y:number)=>minY+maxY-y,outline=(cell:{points:number[][]})=>cell.points.map(([x,y])=>`${x},${up(y)}`).join(' ');
  const name=(i:number)=>continuous?s.name:s.map_tiles[i]?.name??'Map',label=s.tile_size/11;
  return <div className="collection-layout"><div><span className="eyebrow">{modular?'ONGOING TILE PROJECT':'YOUR COLLECTION'}</span><h3>{continuous?'Your continuous map':'Your collection of places'}</h3><p>{s.map_tiles.length} {continuous?(s.map_tiles.length===1?'map tile':'map tiles'):(s.map_tiles.length===1?'place':'places')} · {s.width.toFixed(1)} × {s.height.toFixed(1)} mm · north at the top</p></div><svg viewBox={`${minX-8} ${minY-8} ${maxX-minX+16} ${maxY-minY+16}`} role="group" aria-label="Wall arrangement, north at the top">
    {cells.map((cell,i)=><g key={s.map_tiles[i]?.id??i} role="button" tabIndex={0} aria-label={`Edit tile ${i+1}: ${name(i)}`} aria-pressed={i===s.active_tile} onClick={()=>onTile(i)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onTile(i);}}}><polygon points={outline(cell)} fill={s.colour_ground} stroke={i===s.active_tile?'#ac412b':s.colour_frame} strokeWidth={i===s.active_tile?2:1}/><text x={cell.x} y={up(cell.y)-label*.2} textAnchor="middle" fontSize={label*1.6} fontWeight={700} fill="#20372c">{i+1}</text><text x={cell.x} y={up(cell.y)+label*1.3} textAnchor="middle" fontSize={label} fill="#20372c">{name(i).length>14?name(i).slice(0,13)+'…':name(i)}</text>{pucks&&<rect x={cell.x-15} y={up(cell.y)-15} width={30} height={30} rx={4} fill="none" stroke="#344b40" strokeDasharray="2 1.5" strokeWidth={.5}/>}{s.mount_mode==='magnets'&&[-.23,.23].map(f=><circle key={f} cx={cell.x+s.tile_size*f} cy={up(cell.y)} r={s.magnet_diameter/2} fill="none" stroke="#344b40" strokeDasharray="1 1" strokeWidth={.4}/>)}</g>)}
    {additions.map(({position,cell})=><g key={position.join(',')} className="wall-addition" role="button" tabIndex={0} aria-label={`Add a tile ${position[0]<0?'to the south':position[1]<0?'to the west':`at row ${position[0]+1}, column ${position[1]+1}`}`} onClick={()=>onAdd?.(position)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onAdd?.(position);}}}><polygon points={outline(cell)} fill="#f7f8f3" stroke="#809285" strokeDasharray="3 2" strokeWidth={.7}/><Plus x={cell.x-6} y={up(cell.y)-6} width={12} height={12} stroke="#344b40"/></g>)}
  </svg>{!modular&&onGrow&&<div className="wall-grow-actions"><button type="button" disabled={s.collection_columns>=6} onClick={()=>onGrow('column')}>Add column</button><button type="button" disabled={s.collection_rows>=6} onClick={()=>onGrow('row')}>Add row</button></div>}
  {modular&&onRemove&&s.map_tiles.length>1&&<div className="wall-grow-actions"><button type="button" onClick={()=>onRemove(s.active_tile)}><Trash2 size={14}/> Remove tile {s.active_tile+1}{continuous?'':` · ${name(s.active_tile)}`}</button></div>}
  <p className="hint">{modular?`Select a + on any side to add a tile there. ${continuous?'The map grows in that direction at the same scale, so tiles you have already printed still match.':'Then choose the new tile’s place.'} Up to 36 tiles, six rows and six columns.`:'Select a tile to choose its location.'}{s.mount_mode==='magnets'?' Dashed circles are magnet positions.':''}{pucks?' The dashed square is the wall puck behind each tile.':''} Terrain appears after generation.</p></div>;
}
