import { Grid2X2, Hexagon, Map, Puzzle, Shuffle } from 'lucide-react';
import type { Settings } from './types';
import { collection, resizeCollection } from './formats';
import { puzzlePresets } from './puzzle';
import { NumberField } from './Controls';
export default function FormatEditor({settings:s,onChange}:{settings:Settings;onChange:(v:Partial<Settings>)=>void}) {
  const update=(v:Partial<Settings>)=>onChange(resizeCollection(s,v));
  return <div className="control-block format-editor">
    {collection(s) && <><h3>Tile shape</h3><div className="segmented" role="group" aria-label="Tile shape"><button type="button" aria-pressed={s.map_format === 'mini_tiles'} onClick={() => update({ map_format: 'mini_tiles' })}><Grid2X2 size={17}/>Square</button><button type="button" aria-pressed={s.map_format === 'hexagons'} onClick={() => update({ map_format: 'hexagons' })}><Hexagon size={17}/>Hexagon</button></div></>}
    {s.map_format === 'artwork' && s.project_type === 'modular' && <><h3>Continuous map grid</h3><p className="hint">One map across joined tiles. The outer frame prints separately. Change the project type to use removable maps of different places.</p><div className="two-col"><NumberField label="Wall columns" value={s.columns} min={1} max={6} integer onChange={columns => onChange({ layout: 'manual', columns })}/><NumberField label="Wall rows" value={s.rows} min={1} max={6} integer onChange={rows => onChange({ layout: 'manual', rows })}/></div></>}
    {collection(s)&&<><p className="hint">Choose a tile in Place or click it in the artwork layout. Locations and personal details belong to the selected tile; styles and colours apply across the wall.</p><div className="two-col">
      <NumberField label="Tile width · mm" value={s.tile_size} min={60} max={160} onChange={tile_size=>update({tile_size})}/>
      <NumberField label="Space between tiles · mm" value={s.tile_gap} min={4} max={20} onChange={tile_gap=>update({tile_gap})}/>
      <NumberField label="Collection columns" value={s.collection_columns} min={1} max={6} integer onChange={collection_columns=>update({collection_columns})}/>
      <NumberField label="Collection rows" value={s.collection_rows} min={1} max={6} integer onChange={collection_rows=>update({collection_rows})}/>
    </div><p className="hint" role="status">{s.map_tiles.length} maps · {s.width.toFixed(1)} × {s.height.toFixed(1)} mm overall. {s.map_format==='hexagons'?'Each hexagon has a matching holder.':'One surround holds the removable inserts; larger surrounds split for your printer.'}</p><p className="hint">Adding rows or columns keeps your existing tiles in place. Reducing the grid removes outside tiles; Undo restores them.</p></>}
    {s.map_format==='jigsaw'&&<>
      <h3><Puzzle size={18}/> Build your jigsaw</h3><p className="hint">Pick a challenge, then make the pattern your own. Your place continues across every piece.</p>
      <div className="puzzle-presets" role="group" aria-label="Puzzle difficulty">{puzzlePresets(s).map(p=><button type="button" key={p.label} aria-pressed={s.puzzle_columns===p.columns&&s.puzzle_rows===p.rows} onClick={()=>update({puzzle_columns:p.columns,puzzle_rows:p.rows})}><strong>{p.label}</strong><span>{p.count} pieces · {p.columns} × {p.rows}</span></button>)}</div>
      <div className="segmented" role="group" aria-label="Puzzle connectors"><button type="button" aria-pressed={s.puzzle_style==='classic'} onClick={()=>update({puzzle_style:'classic'})}>Classic jigsaw</button><button type="button" aria-pressed={(s.puzzle_style??'rounded')==='rounded'} onClick={()=>update({puzzle_style:'rounded'})}>Round tabs</button></div>
      {s.puzzle_style==='classic'&&<button type="button" className="puzzle-reshuffle" onClick={()=>update({puzzle_seed:(s.puzzle_seed??1)%9999+1})}><Shuffle size={16}/> Reshuffle piece pattern</button>}
      <p className="hint" role="status">{s.puzzle_columns*s.puzzle_rows} pieces · approximately {((s.width-(s.frame_mode==='none'?0:2*s.frame_width))/s.puzzle_columns).toFixed(1)} × {((s.height-(s.frame_mode==='none'?0:2*s.frame_width))/s.puzzle_rows).toFixed(1)} mm each before tabs. {s.puzzle_style==='classic'?`Pattern ${s.puzzle_seed??1} · varied tab directions, sizes and positions.`:'Broad circular connectors for a simpler puzzle.'}</p>
      <details className="advanced"><summary>Custom grid & relief</summary><div className="two-col"><NumberField label="Puzzle columns" value={s.puzzle_columns} min={2} max={10} integer onChange={puzzle_columns=>update({puzzle_columns})}/><NumberField label="Puzzle rows" value={s.puzzle_rows} min={1} max={10} integer onChange={puzzle_rows=>update({puzzle_rows})}/></div><NumberField label="Puzzle relief · mm" value={s.puzzle_relief} min={.2} max={1.2} step={.1} onChange={puzzle_relief=>update({puzzle_relief})}/></details>
      <p className="hint">A sturdy 3 mm flat base plus at most {s.puzzle_relief} mm of map detail. Print the included puzzle-fit pair first to check your printer's fit.</p>
    </>}
  </div>;
}
export function TilePicker({settings:s,onChange}:{settings:Settings;onChange:(v:Partial<Settings>)=>void}) {
  if(!collection(s))return null;
  return <div className="control-block tile-picker"><h3>Your wall tiles</h3><div className="tile-location-list">{s.map_tiles.map((tile,i)=><button type="button" key={tile.id} aria-pressed={s.active_tile===i} onClick={()=>onChange({active_tile:i,name:tile.name,bounds:tile.bounds,markers:tile.markers,trails:tile.trails,custom_buildings:tile.custom_buildings??[],reference_image:tile.reference_image??null})}><span>{i+1}</span><strong>{tile.name}</strong></button>)}</div><p className="hint">Editing tile {s.active_tile+1}. Choose its place below. Trails, markers and added buildings belong to this tile.</p></div>;
}
export function MountEditor({settings:s,onChange}:{settings:Settings;onChange:(v:Partial<Settings>)=>void}) {
  return <div className="control-block mount-editor"><h3>{s.map_format==='jigsaw'?'Puzzle tray':'Removable tile holders'}</h3><p className="hint">{s.map_format==='hexagons'?'Matching hexagonal holders keep the tiles interchangeable. Glue holders to a backing board in your chosen arrangement.':s.map_format==='jigsaw'?'A flat tray and raised surround support the assembled pieces. Choose No frame for loose puzzle pieces.':'The collection surround has a supported seat for each map. Larger surrounds print as plates to glue onto a backing board.'}</p>
  {collection(s)&&<><div className="segmented" role="group" aria-label="Tile mounting"><button type="button" aria-pressed={s.mount_mode==='seat'} onClick={()=>onChange({mount_mode:'seat'})}>Lift-out seat</button><button type="button" aria-pressed={s.mount_mode==='magnets'} onClick={()=>onChange({mount_mode:'magnets',base:Math.max(s.base,s.magnet_depth+s.magnet_clearance+1.2)})}>Magnet pockets</button></div>{s.mount_mode==='magnets'&&<><div className="two-col"><NumberField label="Magnet diameter · mm" value={s.magnet_diameter} min={3} max={12} onChange={magnet_diameter=>onChange({magnet_diameter})}/><NumberField label="Magnet thickness · mm" value={s.magnet_depth} min={1} max={4} onChange={magnet_depth=>onChange({magnet_depth,base:Math.max(s.base,magnet_depth+s.magnet_clearance+1.2)})}/><NumberField label="Pocket allowance · mm" value={s.magnet_clearance} min={.05} max={.5} step={.05} onChange={magnet_clearance=>onChange({magnet_clearance})}/></div><p className="hint">Two blind pockets per tile and two per holder. Glue in disc magnets with matching polarity. Print Magnet_Fit first; magnets and adhesive are not supplied.</p></>}</>}
  {s.map_format==='jigsaw'&&<NumberField label="Puzzle seam clearance · mm" value={s.puzzle_clearance} min={.1} max={.6} step={.05} onChange={puzzle_clearance=>onChange({puzzle_clearance})}/>}
  </div>;
}
